<?php
/**
 * Configuration Save Handler
 * 
 * Processes the wizard form submission, generates config.php,
 * initializes the database, and sets up the system
 * 
 * @package    VisitorManagement
 * @author     Yeyland Wutani LLC
 * @version    1.0.0
 */

header('Content-Type: application/json');

error_reporting(E_ALL);
ini_set('display_errors', '0');

$response = ['success' => false];

try {
    // Validate request method
    if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
        throw new Exception('Invalid request method');
    }
    
    // Collect form data
    $config = [
        'org_name' => $_POST['org_name'] ?? '',
        'org_short_name' => $_POST['org_short_name'] ?? '',
        'org_tagline' => $_POST['org_tagline'] ?? 'Welcome to our facility',
        'timezone' => $_POST['timezone'] ?? 'America/Los_Angeles',
        'color_primary' => $_POST['color_primary'] ?? '#0066CC',
        'color_secondary' => $_POST['color_secondary'] ?? '#0052A3',
        'visitor_mode' => $_POST['visitor_mode'] ?? 'both',
        'orientation_method' => $_POST['orientation_method'] ?? 'none',
        'external_form_url' => $_POST['external_form_url'] ?? '',
        'recent_visits_limit' => (int)($_POST['recent_visits_limit'] ?? 20),
        'auto_purge_months' => (int)($_POST['auto_purge_months'] ?? 24),
        'admin_username' => $_POST['admin_username'] ?? 'admin',
        'admin_password' => $_POST['admin_password'] ?? ''
    ];
    
    // Validate required fields
    $required = ['org_name', 'org_short_name', 'timezone', 'admin_username', 'admin_password'];
    foreach ($required as $field) {
        if (empty($config[$field])) {
            throw new Exception("Required field missing: $field");
        }
    }
    
    // Handle logo upload
    $logoPath = 'assets/logo.svg';
    if (isset($_FILES['logo_file']) && $_FILES['logo_file']['error'] === UPLOAD_ERR_OK) {
        $uploadDir = dirname(__DIR__) . '/assets/';
        if (!is_dir($uploadDir)) {
            mkdir($uploadDir, 0755, true);
        }
        
        $extension = strtolower(pathinfo($_FILES['logo_file']['name'], PATHINFO_EXTENSION));
        $allowedExtensions = ['svg', 'png', 'jpg', 'jpeg'];
        
        if (!in_array($extension, $allowedExtensions)) {
            throw new Exception('Invalid logo file type');
        }
        
        $logoFilename = 'logo.' . $extension;
        $logoPath = 'assets/' . $logoFilename;
        
        if (!move_uploaded_file($_FILES['logo_file']['tmp_name'], $uploadDir . $logoFilename)) {
            throw new Exception('Failed to upload logo file');
        }
    }
    
    // Generate config.php content
    $configPhp = generateConfigFile($config, $logoPath);
    
    // Write config file
    $configPath = dirname(__DIR__) . '/config/config.php';
    if (!file_put_contents($configPath, $configPhp)) {
        throw new Exception('Failed to write configuration file');
    }
    
    // Initialize database
    initializeDatabase($config);
    
    $response['success'] = true;
    $response['message'] = 'Configuration saved successfully';
    $response['redirect'] = '../admin/';
    
} catch (Exception $e) {
    $response['error'] = $e->getMessage();
    error_log('Setup Error: ' . $e->getMessage());
}

echo json_encode($response);
exit;

/**
 * Generate config.php file content
 * 
 * @param array $config Configuration values from form
 * @param string $logoPath Path to logo file
 * @return string PHP configuration file content
 */
function generateConfigFile($config, $logoPath) {
    $passwordHash = password_hash($config['admin_password'], PASSWORD_BCRYPT);
    
    // Determine visitor types based on mode
    if ($config['visitor_mode'] === 'visitors_only') {
        $visitorTypes = <<<'TYPES'
$VISITOR_TYPES = [
    'visitor' => [
        'label' => 'Visitor',
        'requires_orientation' => false,
        'requires_annual_training' => false,
        'video_path' => null
    ]
];
TYPES;
    } else {
        $orientationEnabled = ($config['orientation_method'] !== 'none');
        $videoPath = ($config['orientation_method'] === 'video') ? 'res/orientation.mp4' : 'null';
        $smartsheetUrl = ($config['orientation_method'] === 'external') ? $config['external_form_url'] : '';
        
        $visitorTypes = <<<TYPES
\$VISITOR_TYPES = [
    'visitor' => [
        'label' => 'Visitor (General)',
        'requires_orientation' => false,
        'requires_annual_training' => false,
        'video_path' => null
    ],
    'contractor' => [
        'label' => 'Contractor',
        'requires_orientation' => {$orientationEnabled},
        'requires_annual_training' => true,
        'training_expires_months' => 12,
        'video_path' => {$videoPath},
        'smartsheet_url' => '{$smartsheetUrl}'
    ]
];
TYPES;
    }
    
    $autoPurgeEnabled = ($config['auto_purge_months'] > 0) ? 'true' : 'false';
    
    $php = <<<PHP
<?php
/**
 * Visitor Management System - Configuration
 * 
 * Generated by Setup Wizard on {date('Y-m-d H:i:s')}
 * 
 * @package    VisitorManagement
 * @author     Yeyland Wutani LLC
 * @version    1.0.0
 */

if (!defined('CONFIG_LOADED')) {
    die('Direct access to configuration file is not allowed.');
}

// ORGANIZATION SETTINGS
define('ORG_NAME', '{$config['org_name']}');
define('ORG_SHORT_NAME', '{$config['org_short_name']}');
define('ORG_TAGLINE', '{$config['org_tagline']}');

// BRANDING COLORS
define('COLOR_PRIMARY', '{$config['color_primary']}');
define('COLOR_SECONDARY', '{$config['color_secondary']}');
define('COLOR_ACCENT', '{$config['color_primary']}');
define('COLOR_TEXT_LIGHT', '#FFFFFF');
define('COLOR_TEXT_DARK', '#333333');

// LOGO AND ASSETS
define('LOGO_PATH', '{$logoPath}');

// TIMEZONE
define('TIMEZONE', '{$config['timezone']}');

// DATABASE
define('DB_PATH', __DIR__ . '/../data/visitors.db');

// VISITOR TYPES
{$visitorTypes}

// STAFF CONTACTS
\$STAFF_CONTACTS = [];

// ADMIN AUTH
define('ADMIN_USERNAME', '{$config['admin_username']}');
define('ADMIN_PASSWORD', '{$passwordHash}');

// SESSION SETTINGS
define('SESSION_NAME', 'visitor_mgmt_session');
define('SESSION_LIFETIME', 3600);
define('SESSION_TIMEOUT', 1800);

// DATA RETENTION
define('AUTO_PURGE_ENABLED', {$autoPurgeEnabled});
define('AUTO_PURGE_MONTHS', {$config['auto_purge_months']});
define('AUTO_PURGE_RUN_TIME', '03:00');

// FEATURE FLAGS
define('ENABLE_BADGE_NUMBER', true);
define('ENABLE_VISITOR_CONTACT', true);
define('ENABLE_ORIENTATION_VIDEO', false);
define('ENABLE_TRAINING_MANAGEMENT', true);

// UI CUSTOMIZATION
define('AUTO_REFRESH_INTERVAL', 30);
define('RECENT_VISITS_LIMIT', {$config['recent_visits_limit']});
define('CURRENT_VISITORS_REFRESH', 30);

// LOGGING
define('ENABLE_LOGGING', true);
define('LOG_FILE', __DIR__ . '/../data/system.log');
define('LOG_LEVEL', 'INFO');

// DEBUG MODE (set to false in production!)
define('DEBUG_MODE', false);
define('DISPLAY_ERRORS', false);
?>
PHP;

    return $php;
}

/**
 * Initialize the SQLite database with required tables
 * 
 * @param array $config Configuration values
 * @throws Exception on database errors
 */
function initializeDatabase($config) {
    $dbPath = dirname(__DIR__) . '/data/visitors.db';
    $dataDir = dirname($dbPath);
    
    if (!is_dir($dataDir)) {
        mkdir($dataDir, 0755, true);
    }
    
    $db = new PDO('sqlite:' . $dbPath);
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
    
    // Create visitors table
    $db->exec('
        CREATE TABLE IF NOT EXISTS visitors (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            name TEXT NOT NULL,
            company TEXT,
            contact TEXT,
            visitor_type TEXT NOT NULL,
            who_visiting TEXT,
            badge_number TEXT,
            check_in_time DATETIME NOT NULL,
            check_out_time DATETIME,
            notes TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP
        )
    ');
    
    // Create training table
    $db->exec('
        CREATE TABLE IF NOT EXISTS training (
            id INTEGER PRIMARY KEY AUTOINCREMENT,
            visitor_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            training_date DATE NOT NULL,
            expiration_date DATE,
            completed BOOLEAN DEFAULT 1,
            notes TEXT,
            created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (visitor_id) REFERENCES visitors(id)
        )
    ');
    
    // Create indexes
    $db->exec('CREATE INDEX IF NOT EXISTS idx_visitors_name ON visitors(name)');
    $db->exec('CREATE INDEX IF NOT EXISTS idx_visitors_checkin ON visitors(check_in_time)');
    $db->exec('CREATE INDEX IF NOT EXISTS idx_visitors_type ON visitors(visitor_type)');
    $db->exec('CREATE INDEX IF NOT EXISTS idx_training_name ON training(name)');
    $db->exec('CREATE INDEX IF NOT EXISTS idx_training_expiration ON training(expiration_date)');
    
    // Log database initialization
    $logFile = dirname($dbPath) . '/system.log';
    $logEntry = date('Y-m-d H:i:s') . " [INFO] Database initialized successfully\n";
    file_put_contents($logFile, $logEntry, FILE_APPEND);
}
?>